/-
Copyright (c) 2025 Eric Ling. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Eric Ling
-/

import TDCSG.CompoundSymmetry.TwoDisk
import TDCSG.Planar.Rotations
import Mathlib.GroupTheory.GroupAction.Defs

/-!
# Finiteness Properties of Symmetry Groups

This file establishes fundamental finiteness results for compound symmetry groups
acting on the two-dimensional disk.

## Main Definitions

* `IsFiniteGroup`: A group is finite if its underlying type is finite.
* `HasInfiniteOrbit`: A group action has an infinite orbit if there exists a point
  whose orbit under the action is infinite.
* `CriticalRadius`: The critical radius is the infimum of radii at which the
  compound symmetry group has infinite orbits.

## Main Results

* `finite_groups_with_trivial_action_admit_subsingleton_quotient`: A technical lemma
  showing that finite groups with constrained actions have limited structure.

## References

* [Two-Disk Compound Symmetry Groups](https://arxiv.org/abs/2302.12950v1)
  - Paper's Theorem 1: "There exists some r for which GG_{n1,n2}(r) is infinite
    if and only if lcm(n1,n2) ∉ {2, 3, 4, 6}."
  - This direction ("only if") was proven in the paper via geometric constructions
  - The full formalization requires defining the group generated by genA and genB

## Implementation Notes

The paper's Theorem 1 characterizes which compound symmetry group families have
infinite members. The current formalization focuses on the infrastructure needed
to state and prove this result. The full theorem requires:

1. Formalization of the free group generated by two elements
2. Group presentations and quotients
3. Geometric analysis of when generators commute or have finite order
4. Connection between group finiteness and geometric radius

This development is deferred to future work.

## Tags

symmetry groups, finiteness, group actions, two-dimensional disk
-/

namespace TDCSG

open CompoundSymmetry Planar

variable {X : Type*} [TopologicalSpace X]

/-! ### Finiteness of groups -/

/--
A group is finite if its underlying type is finite.
-/
def IsFiniteGroup (G : Type*) [Group G] : Prop :=
  Finite G

/-! ### Infinite orbits -/

/--
A group action has an infinite orbit if there exists a point whose orbit
under the action is infinite.
-/
def HasInfiniteOrbit (G : Type*) [Group G] (X : Type*) [MulAction G X] : Prop :=
  ∃ x : X, Set.Infinite (MulAction.orbit G x)

/-! ### Critical radius -/

/--
The critical radius is the infimum of radii at which the compound symmetry
group has infinite orbits. This is a key structural invariant in the theory
of two-dimensional compound symmetry groups.
-/
noncomputable def CriticalRadius (G : Type*) [Group G] [MulAction G ℝ²] : ℝ :=
  sInf {r : ℝ | 0 < r ∧ r < 1 ∧ HasInfiniteOrbit G ℝ²}

/-! ### Structural lemmas -/

/--
**Provable variant**: A finite group acting on ℝ² with only finite orbits
has constrained structure.

This is a stepping stone toward formalizing the paper's Theorem 1, which states:
"There exists some r for which GG_{n1,n2}(r) is infinite if and only if
lcm(n1, n2) ∉ {2, 3, 4, 6}."

The current lemma establishes basic facts about finite group actions that will
be needed in the full development.
-/
theorem finite_group_has_finite_orbits
    (G : Type*) [Group G] [Finite G] [MulAction G ℝ²] :
    ∀ x : ℝ², Set.Finite (MulAction.orbit G x) := by
  intro x
  -- The orbit of x is {g • x | g ∈ G}, which is a finite set since G is finite
  exact Finite.finite_mulAction_orbit x

/--
A finite group cannot have infinite orbits in its action on any space.
-/
theorem finite_group_no_infinite_orbits
    (G : Type*) [Group G] [Finite G] [MulAction G ℝ²] :
    ¬ HasInfiniteOrbit G ℝ² := by
  intro ⟨x, hinf⟩
  have hfin := finite_group_has_finite_orbits G x
  exact hinf hfin

end TDCSG
