import Mathlib

/-!
# Two-Disk Compound Symmetry Groups - Basic Definitions

This file contains the basic definitions for two-disk compound symmetry groups,
introduced in the paper "Two-Disk Compound Symmetry Groups" by Hearn et al.

## Main definitions

* `TwoDiskSystem`: A structure containing two disk centers, radii, and rotation counts
* `leftDisk`, `rightDisk`: The closed disks in the plane
* `leftRotation`, `rightRotation`: The generators of the group
* `TwoDiskGroup`: The group generated by the two rotations

## References

* Hearn, R.A., Kretschmer, W., Rokicki, T., Streeter, B., Vergo, E. (2025).
  "Two-Disk Compound Symmetry Groups"
-/

open Complex
open Classical

/-- A two-disk system consists of two overlapping closed disks in the plane,
    centered at (-1, 0) and (1, 0), with specified radii and rotation counts.
    The generators are discrete rotations of these disks. -/
structure TwoDiskSystem where
  /-- Number of discrete rotation positions for the left disk -/
  n₁ : ℕ
  /-- Number of discrete rotation positions for the right disk -/
  n₂ : ℕ
  /-- Radius of the left disk -/
  r₁ : ℝ
  /-- Radius of the right disk -/
  r₂ : ℝ
  /-- Left disk rotation count must be positive -/
  n₁_pos : 0 < n₁
  /-- Right disk rotation count must be positive -/
  n₂_pos : 0 < n₂
  /-- Left disk radius must be positive -/
  r₁_pos : 0 < r₁
  /-- Right disk radius must be positive -/
  r₂_pos : 0 < r₂

namespace TwoDiskSystem

variable (sys : TwoDiskSystem)

/-- The center of the left disk at (-1, 0) -/
def leftCenter : ℂ := -1

/-- The center of the right disk at (1, 0) -/
def rightCenter : ℂ := 1

/-- The left closed disk -/
def leftDisk : Set ℂ :=
  Metric.closedBall leftCenter sys.r₁

/-- The right closed disk -/
def rightDisk : Set ℂ :=
  Metric.closedBall rightCenter sys.r₂

/-- The angle of rotation for the left disk (clockwise, hence negative) -/
noncomputable def leftAngle : ℝ := -2 * Real.pi / sys.n₁

/-- The angle of rotation for the right disk (clockwise, hence negative) -/
noncomputable def rightAngle : ℝ := -2 * Real.pi / sys.n₂

/-- Left disk rotation as multiplication by a unit complex number.
    This rotates points around the left disk center. -/
noncomputable def leftRotation (z : ℂ) : ℂ :=
  if z ∈ sys.leftDisk then
    leftCenter + exp (I * sys.leftAngle) * (z - leftCenter)
  else
    z

/-- Right disk rotation as multiplication by a unit complex number.
    This rotates points around the right disk center. -/
noncomputable def rightRotation (z : ℂ) : ℂ :=
  if z ∈ sys.rightDisk then
    rightCenter + exp (I * sys.rightAngle) * (z - rightCenter)
  else
    z

/-- Inverse left disk rotation. Rotates in the opposite direction. -/
noncomputable def leftRotationInv (z : ℂ) : ℂ :=
  if z ∈ sys.leftDisk then
    leftCenter + exp (-I * sys.leftAngle) * (z - leftCenter)
  else
    z

/-- Inverse right disk rotation. Rotates in the opposite direction. -/
noncomputable def rightRotationInv (z : ℂ) : ℂ :=
  if z ∈ sys.rightDisk then
    rightCenter + exp (-I * sys.rightAngle) * (z - rightCenter)
  else
    z

/-- Notation: GG_{n₁,n₂}(r₁,r₂) -/
notation "GG_{" n₁ "," n₂ "}(" r₁ "," r₂ ")" =>
  TwoDiskSystem.mk n₁ n₂ r₁ r₂ (by omega) (by omega) (by linarith) (by linarith)

/-- Notation: GG_n(r) for the equal-parameter case -/
notation "GG_" n "(" r ")" =>
  TwoDiskSystem.mk n n r r (by omega) (by omega) (by linarith) (by linarith)

/-- The intersection of the two disks -/
def diskIntersection : Set ℂ :=
  sys.leftDisk ∩ sys.rightDisk

/-- A point is in the disk union if it's in either disk -/
def diskUnion : Set ℂ :=
  sys.leftDisk ∪ sys.rightDisk

end TwoDiskSystem

/-- Notation 'a' for the left rotation generator -/
notation "a" => TwoDiskSystem.leftRotation

/-- Notation 'b' for the right rotation generator -/
notation "b" => TwoDiskSystem.rightRotation
