/-
Copyright (c) 2025 Eric Hearn. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Eric Hearn
-/
import TDCSG.Definitions.Geometry
import Mathlib.Algebra.Group.Subgroup.Lattice
import Mathlib.NumberTheory.Real.GoldenRatio

/-!
# Main Theorem: The Compound Symmetry Group GG₅ is Infinite

Theorem 2 from "Two-Disk Compound Symmetry Groups" (arXiv:2302.12950v1).

## Statement

The compound symmetry group GG(5,5) at the critical radius r_crit = √(3 + φ) is infinite.

## Mathematical Background

The compound symmetry group GG(n,n) is the subgroup of bijections of ℂ generated by:
- A_n: rotation by -2π/n about the left disk center (-1)
- B_n: rotation by -2π/n about the right disk center (+1)

where each generator acts as the identity outside its respective disk.

For n = 5 at the critical radius, the group is infinite because it contains
points whose orbits are infinite (proven via interval exchange transformation analysis).

## Key Definitions

This file contains the essential definitions needed to understand the theorem statement.
All definitions are mathematically self-contained and can be understood independently
of the rest of the codebase.
-/

open Real Complex
open TDCSG.Definitions (leftDisk rightDisk leftCenter rightCenter rotateAboutC)

/-! ### Critical Constants -/

/-- The golden ratio φ = (1 + √5)/2.

    This fundamental constant appears in the critical radius formula.
    At radius r_crit = √(3 + φ), the two disks have a precise geometric
    relationship that enables infinite orbits. -/
noncomputable def φ : ℝ := Real.goldenRatio

/-- The critical radius for GG5: r_crit = √(3 + φ).

    This is the unique radius at which the compound symmetry group GG(5,5)
    exhibits infinite behavior. At other radii, the group may be finite. -/
noncomputable def r_crit : ℝ := Real.sqrt (3 + φ)

/-! ### N-fold Generalized Generators

The generators A_n and B_n are piecewise isometries that rotate by -2π/n
(clockwise) inside their respective disks and act as the identity outside.

For n ≥ 1, these satisfy (A_n)^n = (B_n)^n = id, making them order-n elements.
The 5-fold case (n=5) is what we study in GG5.
-/

/-- Generalized generator A_n: rotation by -2π/n (clockwise) about the left disk center (-1).
    Acts as the identity outside the left disk.

    For n ≥ 1, this is an order-n element: (genA_n n r)^n = id.
    The original genA used throughout the codebase is genA_n 5. -/
noncomputable def genA_n (n : ℕ) (r : ℝ) (z : ℂ) : ℂ := by
  classical
  exact if z ∈ leftDisk r then rotateAboutC leftCenter (-2 * π / n) z else z

/-- Generalized generator B_n: rotation by -2π/n (clockwise) about the right disk center (1).
    Acts as the identity outside the right disk.

    For n ≥ 1, this is an order-n element: (genB_n n r)^n = id.
    The original genB used throughout the codebase is genB_n 5. -/
noncomputable def genB_n (n : ℕ) (r : ℝ) (z : ℂ) : ℂ := by
  classical
  exact if z ∈ rightDisk r then rotateAboutC rightCenter (-2 * π / n) z else z

/-! ### The Compound Symmetry Group GG(n,n)

To define GG(n,n) as a formal group, we need:
1. Each generator must be a bijection (proven using the order-n property)
2. The group is the subgroup closure of {A_n, B_n} in Equiv.Perm ℂ

The bijectivity proofs are in Definitions/GroupTheory.lean.
-/

/-- The bijectivity of genA_n for n ≥ 1.

    Proof strategy: Since (genA_n)^n = id, the generator is its own inverse
    (up to iteration), which implies bijectivity.

    The full proof is in Definitions/GroupTheory.lean. -/
axiom genA_n_bijective (n : ℕ) (hn : n ≥ 1) (r : ℝ) : Function.Bijective (genA_n n r)

/-- The bijectivity of genB_n for n ≥ 1.

    Proof strategy: Since (genB_n)^n = id, the generator is its own inverse
    (up to iteration), which implies bijectivity.

    The full proof is in Definitions/GroupTheory.lean. -/
axiom genB_n_bijective (n : ℕ) (hn : n ≥ 1) (r : ℝ) : Function.Bijective (genB_n n r)

/-- Generalized generator A_n as an element of `Equiv.Perm ℂ`.

    Using the bijectivity proof, we can lift genA_n to a permutation. -/
noncomputable def genA_n_perm (n : ℕ) (hn : n ≥ 1) (r : ℝ) : Equiv.Perm ℂ :=
  Equiv.ofBijective (genA_n n r) (genA_n_bijective n hn r)

/-- Generalized generator B_n as an element of `Equiv.Perm ℂ`.

    Using the bijectivity proof, we can lift genB_n to a permutation. -/
noncomputable def genB_n_perm (n : ℕ) (hn : n ≥ 1) (r : ℝ) : Equiv.Perm ℂ :=
  Equiv.ofBijective (genB_n n r) (genB_n_bijective n hn r)

/-- The compound symmetry group GG(n,n) at radius r.

    This is the subgroup of `Equiv.Perm ℂ` generated by the two n-fold
    rotation generators A_n and B_n. For each n ≥ 1 and radius r, we get
    a different group.

    The fundamental question: For which (n, r) is this group finite vs infinite?

    Known results:
    - For most radii, GG(n,n) is finite
    - At certain critical radii, GG(n,n) can be infinite
    - This theorem proves GG(5,5) is infinite at r_crit = √(3 + φ) -/
noncomputable def TwoDiskCompoundSymmetryGroup (n : ℕ) (hn : n ≥ 1) (r : ℝ) :
    Subgroup (Equiv.Perm ℂ) :=
  Subgroup.closure {genA_n_perm n hn r, genB_n_perm n hn r}

/-- GG5: The compound symmetry group GG(5,5) at the critical radius.

    This is the main object of study in the paper. It is the 5-fold
    specialization: TwoDiskCompoundSymmetryGroup with n=5 and r=r_crit.

    The theorem below states that this specific group is infinite. -/
noncomputable def GG5_At_Critical_radius : Subgroup (Equiv.Perm ℂ) :=
  TwoDiskCompoundSymmetryGroup 5 (by norm_num) r_crit

/-! ### The Main Theorem -/

/-- **Theorem 2**: The compound symmetry group GG₅ at the critical radius is infinite.

    This is the precise statement from arXiv:2302.12950v1:
    The group generated by the two 5-fold rotation generators A and B,
    where each acts as the identity outside its disk, is an infinite group.

    Formally: `GG5_At_Critical_radius : Subgroup (Equiv.Perm ℂ)` has infinitely many elements.

    Proof strategy (in ProofOfMainTheorem.lean):
    1. Construct a specific point z whose orbit under GG5 is infinite
    2. Show this orbit analysis reduces to an interval exchange transformation
    3. Use ergodic theory to prove the IET has an infinite orbit
    4. Conclude that GG5 must be infinite (finite group ⟹ finite orbits) -/
def StatementOfTheorem : Prop :=
  Infinite GG5_At_Critical_radius
