/-
Copyright (c) 2025 Eric Hearn. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Eric Hearn
-/
import TDCSG.Definitions.Geometry
import TDCSG.Definitions.GroupTheory

/-!
# Main Theorem: The Compound Symmetry Group GG₅ is Infinite

Theorem 2 from "Two-Disk Compound Symmetry Groups" (arXiv:2302.12950v1).

## Statement

The compound symmetry group GG(5,5) at the critical radius r_crit = √(3 + φ) is infinite.

## Mathematical Background

The compound symmetry group GG(n,m) is the subgroup of bijections of ℂ generated by:
- A: rotation by -2π/n about the left disk center (-1)
- B: rotation by -2π/m about the right disk center (+1)

where each generator acts as the identity outside its respective disk.

For GG(5,5) at the critical radius, the group is infinite because it contains
points whose orbits are infinite (proven via interval exchange transformation analysis).

## Formalization

- `GG5` : The compound symmetry group as `Subgroup (Equiv.Perm ℂ)`
- `StatementOfTheorem` : The proposition that GG5 is infinite
-/

open TDCSG.Definitions

/-- Configuration for the GG(5,5) two-disk system at critical radius. -/
noncomputable def GG5_critical :
    CompoundSymmetry.TwoDiskSystem where
  r1 := r_crit
  r2 := r_crit
  n1 := 5
  n2 := 5

/-- **Theorem 2**: The compound symmetry group GG₅ at the critical radius is infinite.

    This is the precise statement from arXiv:2302.12950v1:
    The group generated by the two 5-fold rotation generators A and B,
    where each acts as the identity outside its disk, is an infinite group.

    Formally: `GG5 : Subgroup (Equiv.Perm ℂ)` has infinitely many elements. -/
def StatementOfTheorem : Prop :=
  Infinite GG5_At_Critical_radius
