/-
Copyright (c) 2024 Eric Vergo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Eric Vergo
-/
import TDCSG.Definitions.Geometry
import TDCSG.Definitions.GroupAction
import Mathlib.Algebra.Group.Subgroup.Lattice

/-!
# Main Theorem Statement

This file contains the statement of the main theorem from arXiv:2302.12950v1:
the compound symmetry group GG(5,5) at the critical radius is infinite.

## Main definitions

- `genA_n_perm n hn r`: The n-fold rotation generator A as a permutation of ℂ
- `genB_n_perm n hn r`: The n-fold rotation generator B as a permutation of ℂ
- `TwoDiskCompoundSymmetryGroup n hn r`: The group GG(n,n) generated by A and B at radius r
- `GG5_At_Critical_radius`: The group GG(5,5) at the critical radius r_crit = √(3 + φ)
- `StatementOfTheorem`: The proposition that GG5_At_Critical_radius is infinite

## References

* [arXiv:2302.12950v1](https://arxiv.org/abs/2302.12950)
-/

open Real Complex
open scoped Circle
open TDCSG.Definitions (leftDisk rightDisk leftCenter rightCenter rotateAboutC
  genA_n genB_n genA_n_bijective genB_n_bijective r_crit φ)

/-- The n-fold rotation generator A as a permutation of ℂ.
Rotates by -2π/n about the left center (-1) inside the left disk, identity outside. -/
noncomputable def genA_n_perm (n : ℕ) (hn : n ≥ 1) (r : ℝ) : Equiv.Perm ℂ :=
  Equiv.ofBijective (genA_n n r) (genA_n_bijective n hn r)

/-- The n-fold rotation generator B as a permutation of ℂ.
Rotates by -2π/n about the right center (+1) inside the right disk, identity outside. -/
noncomputable def genB_n_perm (n : ℕ) (hn : n ≥ 1) (r : ℝ) : Equiv.Perm ℂ :=
  Equiv.ofBijective (genB_n n r) (genB_n_bijective n hn r)

/-- The two-disk compound symmetry group GG(n,n) at radius r.
This is the subgroup of permutations of ℂ generated by the n-fold generators A and B. -/
noncomputable def TwoDiskCompoundSymmetryGroup (n : ℕ) (hn : n ≥ 1) (r : ℝ) :
    Subgroup (Equiv.Perm ℂ) :=
  Subgroup.closure {genA_n_perm n hn r, genB_n_perm n hn r}

/-- The compound symmetry group GG(5,5) at the critical radius r_crit = √(3 + φ),
where φ = (1 + √5)/2 is the golden ratio. -/
noncomputable def GG5_At_Critical_radius : Subgroup (Equiv.Perm ℂ) :=
  TwoDiskCompoundSymmetryGroup 5 (by norm_num) r_crit

/-- **Main Theorem**: The compound symmetry group GG₅ at the critical radius is infinite. -/
def StatementOfTheorem : Prop :=
  Infinite GG5_At_Critical_radius
