/-
Copyright (c) 2024 Eric Vergo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Eric Vergo
-/
import TDCSG.MainTheorem
import TDCSG.Proofs.GroupTheory

/-!
# Proof of Main Theorem

This file contains the complete proof that `GG₅` at the critical radius `r = √(3 + φ)` is infinite,
where `φ = (1 + √5)/2` is the golden ratio.

This is the main result of the paper:
> **Theorem** (Two-Disk Compound Symmetry Groups, Section "Geometric Constructions"):
> *GG₅ is infinite at r = √(3 + φ).*

## Mathematical Context

A *compound symmetry group* is generated by isometries of overlapping metric subspaces.
The two-disk system `GG_{n₁,n₂}(r₁,r₂)` consists of two closed disks centered at `(-1, 0)` and
`(1, 0)` with radii `r₁` and `r₂`, and generators `a`, `b` being rotations by `-2π/n₁` and
`-2π/n₂` respectively. The group operation is function composition on the left.

The family `GG₅` (where `n₁ = n₂ = 5`) has a *critical radius* `r_c` such that the group is
finite for `r < r_c` and infinite for `r ≥ r_c`. This file proves that at the geometrically
determined value `r_c = √(3 + φ) ≈ 2.149`, the group is indeed infinite.

## Proof Strategy

The proof follows the geometric construction from the paper, which analyzes how specific
group elements act on the line segment `E'E` in the complex plane.

**Key geometric setup** (referring to Figure 5a in the paper):
- Let `ζ₅ = e^(2πi/5)` be a primitive 5th root of unity
- Point `E = ζ₅ - ζ₅²` lies on the boundary of the left disk (with `|E+1| = r_crit`)
- Point `E' = -conj(E)` is symmetric across the imaginary axis
- Points `F = 1 - ζ₅ + ζ₅² - ζ₅³` and `G = 2F - E` lie on segment `E'E`

**The induced IET (Interval Exchange Transformation)**:

The segment `E'E` is partitioned into three intervals `[E', F')`, `[F', G')`, `[G', E)`,
and three specific group element sequences act as translations on these intervals:

1. `a⁻²b⁻¹a⁻¹b⁻¹` translates `[E', F')` to `[G, F]`
2. `abab²` translates `[F', G')` to `[F, E]`
3. `aba b⁻¹a⁻¹b⁻¹` translates `[G', E)` to `[E', G]`

**Why the group is infinite**:

The crucial observation is that the ratio `|E - E'| / |F - F'| = φ` (the golden ratio).
Since `φ` is irrational, iterating this piecewise translation never returns to the starting
point. Therefore, the origin has an infinite orbit under the group.

**Proof structure in Lean**:
1. `GG5_IET_has_infinite_orbit`: Constructs a point `x₀ ∈ [0, 1)` with infinite IET orbit
   (proved via golden ratio irrationality in `Proofs/OrbitInfinite.lean`)
2. `IET_orbit_infinite_implies_group_orbit_infinite`: Lifts infinite IET orbits to group orbits
   (proved via word correspondence in `Proofs/IETOrbit.lean`)
3. `orbit_eq_MulAction_orbit`: Identifies word-based orbits with `MulAction` orbits
   (proved in `Proofs/GroupTheory.lean`)
4. `infinite_orbit_implies_infinite_group`: Groups with infinite orbits are infinite
   (proved in `Proofs/GroupTheory.lean`)

## Main Declarations

- `GG5_infinite_at_critical_radius`: The main theorem proving `StatementOfTheorem`

## References

* Hearn, Kretschmer, Rokicki, Streeter, Vergo. "Two-Disk Compound Symmetry Groups".
  Bridges 2024 Conference Proceedings.
* Figure 5a in the paper shows the geometric construction
* The proof follows Section "Geometric Constructions", specifically the `n = 5` case
-/

open TDCSG.Definitions TDCSG.CompoundSymmetry.GG5

/--
**Main Theorem**: The compound symmetry group `GG₅` at the critical radius `r = √(3 + φ)` is infinite.

This corresponds to the theorem in Section "Geometric Constructions" of the paper:
"GG₅ is infinite at r = √(3 + φ)."

**Proof outline**:
1. From `GG5_IET_has_infinite_orbit`, obtain a point `x₀ ∈ [0, 1)` whose orbit under the
   induced interval exchange transformation (IET) is infinite.
2. Using `IET_orbit_infinite_implies_group_orbit_infinite`, lift the infinite IET orbit
   to show that `segmentPoint x₀` (the corresponding point on the segment `E'E` in ℂ)
   has an infinite orbit under the word-based group action.
3. Apply `orbit_eq_MulAction_orbit` to rewrite the word-based orbit as a `MulAction.orbit`,
   confirming that `segmentPoint x₀` has infinite orbit under the formal group structure.
4. Conclude via `infinite_orbit_implies_infinite_group`: any group admitting a point with
   infinite orbit must itself be infinite.

The key mathematical insight is that the golden ratio structure of the IET intervals
(with lengths in ratio `1 : φ : φ²`) combined with the irrationality of `φ` guarantees
that no orbit can be periodic, hence some orbits must be infinite.

**Paper reference**: Figure 5a, Section "Geometric Constructions", n = 5 case.
-/
theorem GG5_infinite_at_critical_radius : StatementOfTheorem := by
  -- Step 1: Get a point x₀ in [0,1) with infinite IET orbit
  obtain ⟨x₀, hx₀_mem, hx₀_inf⟩ := GG5_IET_has_infinite_orbit
  -- Step 2: Lift the infinite IET orbit to an infinite word-based group orbit
  have h_word_inf : (orbit r_crit (segmentPoint x₀)).Infinite :=
    IET_orbit_infinite_implies_group_orbit_infinite x₀ hx₀_mem hx₀_inf
  -- Step 3: Rewrite word orbit as MulAction orbit
  rw [orbit_eq_MulAction_orbit] at h_word_inf
  -- Step 4: Conclude the group is infinite
  exact infinite_orbit_implies_infinite_group (segmentPoint x₀) h_word_inf
