/-
Copyright (c) 2024 Eric Vergo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Eric Vergo
-/
import Mathlib.Dynamics.PeriodicPts.Defs
import TDCSG.Definitions.IET

/-!
# Real Dynamics for Two-Disk Compound Symmetry Groups

This file defines real-valued dynamical systems concepts used to analyze the
interval exchange transformation (IET) arising from the GG5 two-disk compound
symmetry group. The central question is whether points have finite or infinite
orbits under the IET, which relates directly to whether the compound symmetry
group is finite or infinite at a given radius.

## Mathematical Context

Two-disk compound symmetry groups GG_{n}(r) are generated by discrete rotations
of overlapping disks. At the critical radius r_c, the orbit structure undergoes
a phase transition from finite to infinite. For GG5, the critical radius is
r_c = sqrt(3 + phi) where phi is the golden ratio.

The IET studied here is induced by the action of the generator ab^{-1} on a
fundamental domain. Points with infinite orbits under this IET correspond to
points in the characteristic fractal of GG5.

## Main definitions

* `RealDynamics.orbitSet f x`: The orbit {f^n(x) | n in N} of point x under f
* `RealDynamics.HasInfiniteOrbit f x`: No point in the orbit of x is periodic
* `TDCSG.Definitions.GG5_displacement x`: Displacement function for GG5 IET
* `TDCSG.Definitions.cumulative_displacement y n`: Accumulated displacement over n steps

## Implementation notes

The displacement function partitions [0,1] into three intervals corresponding to
the three exchange pieces of the IET. Each interval has a constant displacement
derived from the golden ratio geometry of the n=5 case.

## References

* Hearn et al., "Two-Disk Compound Symmetry Groups" (Section on GG5 proof)
* The proof that GG5 is infinite at r = sqrt(3 + phi) uses a three-piece
  piecewise translation that maps the segment E'E onto itself with irrational
  scaling, generating infinitely many distinct orbit points.
-/

namespace RealDynamics

open Function Set

/-- The forward orbit of a point `x` under repeated application of `f : R -> R`.

For an interval exchange transformation `f`, this is the set of all points reachable
from `x` by iterating `f` any number of times. The orbit structure determines whether
the underlying dynamical system (and corresponding two-disk compound symmetry group)
is finite or infinite.

Mathematically: `orbitSet f x = {f^n(x) | n in N}` where `f^n` denotes n-fold
composition of `f` with itself.

Example: For the GG5 IET at critical radius, points on the segment E'E have
orbits that densely fill this segment, while points outside have finite orbits. -/
def orbitSet (f : ℝ → ℝ) (x : ℝ) : Set ℝ :=
  {y | ∃ (n : ℕ), (f^[n]) x = y}

/-- A point `x` has infinite orbit under `f` if no point in its forward orbit is periodic.

This is the key property distinguishing points in the characteristic fractal from
ordinary points. At the critical radius of a two-disk compound symmetry group:
- Points with `HasInfiniteOrbit` lie in the characteristic fractal
- Points without this property have finite orbits

For GG5 at r = sqrt(3 + phi), the three-piece piecewise translation induces
dynamics where points on the fundamental segment E'E satisfy this property
because the ratio |E-E'|/|F-F'| = phi is irrational, preventing periodic returns.

Note: This is equivalent to saying the orbit is infinite as a set, but the
formulation via `periodicPts` connects to Mathlib's dynamical systems API. -/
def HasInfiniteOrbit (f : ℝ → ℝ) (x : ℝ) : Prop :=
  ∀ y ∈ orbitSet f x, y ∉ Function.periodicPts f

end RealDynamics

namespace TDCSG.Definitions

open RealDynamics

/-- The displacement function for the GG5 interval exchange transformation.

This piecewise constant function assigns a translation amount to each of the three
intervals that partition [0, 1]. The displacements are derived from the geometry
of the five-fold rotation at critical radius r = sqrt(3 + phi).

The three cases correspond to segments E'F', F'G', and G'E from the paper's proof:
- On [0, length1): displacement by `displacement0`
- On [length1, length1 + length2): displacement by `displacement1`
- On [length1 + length2, 1]: displacement by `displacement2`

These displacements implement the three transformations:
1. a^{-2} b^{-1} a^{-1} b^{-1} translates E'F' to GF
2. a b a b^2 translates F'G' to FE
3. a b a b^{-1} a^{-1} b^{-1} translates G'E to E'G

The key property is that |F-F'| and |E-G| are incommensurable with |E-E'|,
since |E-E'|/|F-F'| = phi (the golden ratio), ensuring infinite orbits. -/
noncomputable def GG5_displacement (x : ℝ) : ℝ :=
  if x < length1 then displacement0
  else if x < length1 + length2 then displacement1
  else displacement2

/-- Cumulative displacement after `n` iterations of the GG5 interval exchange transformation.

Computes the total signed displacement accumulated by starting at point `y` and applying
the IET `n` times, summing the displacement at each step:
  cumulative_displacement y n = sum_{k=0}^{n-1} GG5_displacement(IET^k(y))

This function tracks how far a point has traveled from its starting position after
`n` iterations. For points with infinite orbits, this cumulative displacement grows
without bound as n increases (though not monotonically, due to the piecewise nature
of the displacement function).

The cumulative displacement is useful for analyzing the symbolic dynamics of the IET
and for proving properties about orbit closure and density. -/
noncomputable def cumulative_displacement (y : ℝ) (n : ℕ) : ℝ :=
  ∑ k ∈ Finset.range n, GG5_displacement ((GG5_induced_IET.toFun^[k]) y)

end TDCSG.Definitions
